services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: urbetrack-md5-api:1.0.3
    container_name: urbetrack-md5-api
    expose:
      - "8000"

  nginx:
    image: nginx:1.27-alpine
    container_name: urbetrack-md5-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
